export { UR } from '@ngraveio/bc-ur'

export enum URType {
  CryptoPSBT = 'crypto-psbt',
  CryptoMultiAccounts = 'crypto-multi-accounts',
  CryptoHDKey = 'crypto-hdkey',
  CryptoAccount = 'crypto-account',
  BtcSignature = 'btc-signature',
  ArweaveCryptoAccount = 'arweave-crypto-account',
  EthSignature = 'eth-signature',
  SolSignature = 'sol-signature',
  StellarSignature = 'stellar-signature',
  CosmosSignature = 'cosmos-signature',
  EvmSignature = 'evm-signature',
  AptosSignature = 'aptos-signature',
  CardanoSignature = 'cardano-signature',
  CardanoSignDataSignature = 'cardano-sign-data-signature',
  CardanoCatalystSignature = 'cardano-catalyst-voting-registration-signature',
  TronSignature = 'keystone-sign-result',
  KeystoneSignResult = 'keystone-sign-result',
  NearSignature = 'near-signature',
  ArweaveSignature = 'arweave-signature',
  SuiSignature = 'sui-signature',
  XrpAccount = 'bytes',
  XrpSignRequest = 'bytes',
  XrpSignature = 'bytes',
  TonSignature = 'ton-signature',
}
